application: mcberros-hello-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.app

- url: /problem2
  script: problem2.problem2.app

- url: /example_cookie
  script: example_cookie.example_cookie.app

- url: /art
  script: art.art.app

- url: /blog
  script: blog.blog.app

- url: /blog/.json
  script: blog.blog.app

- url: /blog/signup
  script: blog.signup.app

- url: /blog/login
  script: blog.signup.app

- url: /blog/logout
  script: blog.signup.app

- url: /blog/welcome
  script: blog.signup.app

- url: /blog/users
  script: blog.signup.app

- url: /blog/.*
  script: blog.blog.app

- url: /problem1/.*
  script: problem1.problem1.app

- url: /problem2_2/.*
  script: problem2.problem2_2.app

- url: /wiki/css
  static_dir: wiki/css

- url: /wiki
  script: wiki.wiki.app

- url: /wiki/.*
  script: wiki.wiki.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
