application: mcberros-hello-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.app

- url: /art
  script: art.app

- url: /blog
  script: blog.app

- url: /blog/.json
  script: blog.app

- url: /blog/signup
  script: signup.app

- url: /blog/login
  script: signup.app

- url: /blog/logout
  script: signup.app

- url: /blog/welcome
  script: signup.app

- url: /blog/users
  script: signup.app

- url: /blog/.*
  script: blog.app

- url: /problem1/.*
  script: problem1.app

- url: /problem2/.*
  script: problem2.app

- url: /problem2_2/.*
  script: problem2_2.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
